version: '3.9'

services:
  db_autoshop:
    image: postgis/postgis:15-3.4-alpine
    container_name: autoshop-5431
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: autoshop
    ports:
      - "5431:5432"
    networks:
      - pg-network
    volumes:
      - postgres_autoshop:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db_autoshop

networks:
  pg-network:
    driver: bridge

volumes:
  postgres_autoshop:
  pgadmin_data:
